BNF

diff --git a/compileCommand b/compileCommand
--- a/compileCommand
+++ b/compileCommand
@@ -1,4 +1,34 @@
 #!/bin/sh
+
+if [ -n "$JACC_PATH" ] ; then
+    echo $JACC_PATH
+else
+    echo "please set JACC_PATH variable"
+    exit 1
+fi
+
+# Determine the Java command to use to start the JVM.
+if [ -n "$JAVA_HOME" ] ; then
+    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
+        # IBM's JDK on AIX uses strange locations for the executables
+        JAVACMD="$JAVA_HOME/jre/sh/java"
+    else
+        JAVACMD="$JAVA_HOME/bin/java"
+    fi
+    if [ ! -x "$JAVACMD" ] ; then
+        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME
+
+Please set the JAVA_HOME variable in your environment to match the
+location of your Java installation."
+    fi
+else
+    JAVACMD="java"
+    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+
+Please set the JAVA_HOME variable in your environment to match the
+location of your Java installation."
+fi
+
 ./jacc-bin/jacc -vf ./BNF/CommandAward.jacc -e ./BNF/SyntaxErrors.errs
 cp -f ./BNF/CommandParser.java ./BNF/CommandTokens.java ./src/main/java/cn/boxfish/jack/parser/
 
